config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  get 'projects/:id/statements', to: 'statements#index', as: 'project_statements'
  get 'projects/:id/statements/:date', to: 'statements#show', as: 'project_statement'
  get 'projects/:id/statements/:date/transactions', to: 'statements#transactions', as: 'statement_transactions'
  get 'projects/:id/statements/:date/summary', to: 'statements#summary', as: 'statement_summary'


  resources :projects do
    member do
      get 'backup', to: 'backup#index'
      get 'backup/download', to: 'backup#download'
      post 'backup/restore', to: 'backup#restore'

      get 'train', to: 'training#train'
      get 'preview', to: 'training#preview', as: 'training_preview'
      post 'classify', to: 'training#classify'

      get 'categories'

      get 'reports/spend', to: 'reports#spend'
      get 'reports/spend_data', to: 'reports#spend_data'
      get 'reports/balance', to: 'reports#balance'
      get 'reports/balance_data', to: 'reports#balance_data'
      get 'reports/income_outgoings', to: 'reports#income_outgoings'
      get 'reports/income_outgoings_data', to: 'reports#income_outgoings_data'
    end

    resources :accounts, shallow: true do
      resources :transactions, shallow: true do
        collection do
          get 'statement'
          get 'statement_summary'
        end
        member do
          post 'verify'
        end
      end
      member do
        get 'import_statement'
        post 'upload_statement'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_transactions_table.html.erb
<table class="transactions">
  <thead>
    <tr>
      <th class="date">Date</th>
      <th class="description">Description</th>
      <th class="value">Value</th>
      <th class="balance">Balance</th>
      <th class="category">Category</th>
      <th class="predicted_category">Prediction</th>
      <th class="verified">Verify</th>
    </tr>
  </thead>

  <tbody>
    <% transactions.each do |transaction| %>
        <tr class="<%= classify.call(transaction) %>">
          <td><%= transaction.date %></td>
          <td><%= transaction.description %></td>
          <td class="numeric"><%= currency transaction.value %></td>
          <td class="numeric"><%= currency transaction.balance %></td>
          <td>
            <% if editable %>
                <%= form_with(model: transaction, class: 'category') do |form| %>
                    <%= form.text_field :assigned_category, { autocomplete: 'off' } %>
                <% end %>
            <% else %>
              <%= transaction.assigned_category %>
            <% end %>
          </td>
          <td><%= transaction.predicted_category %></td>
          <td>
            <% if editable %>
              <%= form_with(scope: :transaction, url: verify_transaction_path(transaction), class: 'verified') do |form| %>
                  <%= form.check_box :verified, { id: "verified_#{transaction.id}", disabled: !transaction.assigned_category.blank?, tabindex: -1 } %>
                  <label for="verified_<%= transaction.id %>"></label>
              <% end %>
            <% end %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_verification_status.html.erb
<table class="summary">
  <tr>
    <th>
      Verified amounts
    </th>
    <td class="right-align">
      <span class="verified">£</span>
    </td>
    <td class="right-align number">
          <span class="verified">
            <%= currency(verification_state[:verified_spend]) %>
          </span>
    </td>
    <td class="right-align">
          <span class="light verified">
          (<%= verification_state[:percent_verified_spend].round %>%)
          </span>
    </td>
  </tr>
  <% if show_unverified_spend %>
  <tr>
    <th>
      Unverified amounts
    </th>
    <td class="right-align">
      <span class="unverified">£</span>
    </td>
    <td class="right-align number">
          <span class="unverified">
            <%= currency(verification_state[:unverified_spend]) %>
          </span>
    </td>
    <td class="right-align">
          <span class="light unverified">
          (<%= verification_state[:percent_unverified_spend].round %>%)
          </span>
    </td>
  </tr>
  <% end %>
  <tr>
    <td colspan="4">
      <div class="progress verification_state">
        <div class="determinate" style="width: <%= verification_state[:percent_verified_spend] %>%"></div>
      </div>
    </td>
  </tr>
</table>