config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  get 'projects/:id/statements', to: 'statements#index', as: 'project_statements'
  get 'projects/:id/statements/:date', to: 'statements#show', as: 'project_statement'
  get 'projects/:id/statements/:date/transactions', to: 'statements#transactions', as: 'statement_transactions'
  get 'projects/:id/statements/:date/summary', to: 'statements#summary', as: 'statement_summary'


  resources :projects do
    member do
      get 'backup', to: 'backup#index'
      get 'backup/download', to: 'backup#download'
      post 'backup/restore', to: 'backup#restore'

      get 'train', to: 'training#train'
      get 'preview', to: 'training#preview', as: 'training_preview'
      post 'classify', to: 'training#classify'

      get 'categories'

      get 'reports/spend', to: 'reports#spend'
      get 'reports/spend_data', to: 'reports#spend_data'
      get 'reports/balance', to: 'reports#balance'
      get 'reports/balance_data', to: 'reports#balance_data'
      get 'reports/income_outgoings', to: 'reports#income_outgoings'
      get 'reports/income_outgoings_data', to: 'reports#income_outgoings_data'
    end

    resources :accounts, shallow: true do
      resources :transactions, shallow: true do
        collection do
          get 'statement'
          get 'statement_summary'
        end
        member do
          post 'verify'
        end
      end
      member do
        get 'import_statement'
        post 'upload_statement'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :accounts
  has_many :transactions, through: :accounts

  def statements
    Statement.for(self)
  end

  def scan_statement_transactions
    scan_dir = File.join(directory, 'statements')
    statements = Dir.glob("#{scan_dir}/*.csv").map do |filename|
      Statement.new(self, File.basename(filename))
    end
    statements.map{ |statement| statement.scan_transactions }.flatten
  end

  def scan_stored_transactions
    stored_transactions = []
    Dir.glob(File.join(directory, 'transactions/*.yaml')).each do |filename|
      content = YAML.load_file(filename)
      if content['transactions']
        content['transactions'].each do |attrs|
          stored_transactions << transactions.build(attrs)
        end
      end
    end
    stored_transactions
  end

  def categories
    accounts.map{ |account| account.categories }.flatten.uniq
  end

  def verification_state
    VerificationState.new(transactions).compute_state
  end

  def sum_category(category, month_start, account_ids)
    transactions
      .within_month(month_start)
      .joins(:account)
      .where('coalesce(assigned_category, predicted_category) = ?', category)
      .where('account_id in (?)', account_ids)
      .sum("case accounts.account_type when 'credit_card' then -value else value end")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :categories, :verification_state]

  include FormatHelper

  def categories
    respond_to do |format|
      format.json { render json: @project.categories, status: :ok }
    end
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @verification_state = @project.verification_state

    unless @project.transactions.empty?
      charts_to_date = @project.transactions.order('date').last.date
      charts_from_date = (charts_to_date - 90.days).beginning_of_month
      chart_params = 'from_date=' + date_value(charts_from_date) +
        '&to_date=' + date_value(charts_to_date) +
        '&show_total=true';
    end
    chart_account_ids = @project.accounts.map{ |a| "account_ids[]=#{a.id}" }.join('&')

    @balance_chart_url = "#{project_path(@project)}/reports/balance_data/?#{chart_params}"
    @spend_chart_url = "#{project_path(@project)}/reports/spend_data/?#{chart_params}&#{chart_account_ids}"
    @income_outgoings_chart_url = "#{project_path(@project)}/reports/income_outgoings_data/?#{chart_params}&#{chart_account_ids}"
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :directory)
    end
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :directory %>
    <%= form.text_field :directory, id: :project_directory %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/export.html.erb
<h1>Export</h1>

<p>
  <a href="<%= export_project_path(@project, raw: true) %>"
     class="waves-effect waves-light btn"
     download="export.yaml"
  >
    <i class="material-icons left">file_download</i>
    download
  </a>
</p>

<%= text_area_tag(:yaml, @content, class: 'yaml-preview') %>

app/views/projects/index.html.erb
<% breadcrumb :projects %>

<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Directory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.directory %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% breadcrumb :project, @project %>

<p id="notice"><%= notice %></p>

<script type="text/javascript">
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawCharts);

  function drawCharts() {
    var balanceChartDiv = $('#balance_chart');
    balanceChartDiv.css('height', balanceChartDiv.width() * 0.5);
    balanceChartDiv.animate({opacity: 0});

    var spendChartDiv = $('#spend_chart');
    spendChartDiv.css('height', spendChartDiv.width() * 0.5);
    spendChartDiv.animate({opacity: 0});

    var incomeOutgoingsChartDiv = $('#income_outgoings_chart');
    incomeOutgoingsChartDiv.css('height', spendChartDiv.width() * 0.5);
    incomeOutgoingsChartDiv.animate({opacity: 0});

    $.get('<%= @balance_chart_url.html_safe %>', function(jsonData) {
      var data = new google.visualization.DataTable(jsonData);
      var options = {
        legend: 'none',
        chartArea: {
          width: '75%',
          height: '75%'
        }
      };

      var chart = new google.visualization.LineChart(document.getElementById('balance_chart'));

      chart.draw(data, options);
      balanceChartDiv.animate({opacity: 1});
    });

    $.get('<%= @spend_chart_url.html_safe %>', function(jsonData) {
      var data = new google.visualization.DataTable(jsonData);
      var options = {
        legend: 'none',
        chartArea: {
          width: '75%',
          height: '75%'
        },
        isStacked: true
      };

      var chart = new google.visualization.SteppedAreaChart(document.getElementById('spend_chart'));

      chart.draw(data, options);
      spendChartDiv.animate({opacity: 1});
    });

    $.get('<%= @income_outgoings_chart_url.html_safe %>', function(jsonData) {
      var data = new google.visualization.DataTable(jsonData);
      var options = {
        legend: 'none',
        chartArea: {
          width: '75%',
          height: '75%'
        },
        seriesType: 'bars',
        series: {2: {type: 'line'}}
      };

      var chart = new google.visualization.ComboChart(document.getElementById('income_outgoings_chart'));

      chart.draw(data, options);
      incomeOutgoingsChartDiv.animate({opacity: 1});
    });
  }
</script>

<div class="row">
  <div class="col s10">
    <h1><%= @project.name %></h1>
  </div>
  <div class="col s2">
    <%= link_to 'Edit', edit_project_path(@project), class: 'btn-flat right' %>
  </div>
</div>

<div class="divider"></div>

<div class="row section accounts header">
  <div class="col s6">
    <h4>
      Accounts
      <%= link_to 'More →', project_accounts_path(@project), class: 'btn-flat right' %>
    </h4>
  </div>
  <div class="col s6">
    <h4>
      <%= link_to 'Statements →', project_statements_path(@project), class: 'btn-flat right' %>
    </h4>
  </div>
</div>
<div class="row">
  <div class="col s6">
    <div class="collection">
      <% @project.accounts.each do |account| %>
          <a href="<%= account_path(account) %>" class="collection-item">
            <b><%= account.name %></b>
            <br>
            <%= I18n.t account.account_type %>
          </a>
      <% end %>
    </div>
  </div>
  <div class="col s6">
    <%= render partial: 'shared/verification_status',
        locals: { verification_state: @verification_state, show_unverified_spend: true } %>
  </div>
</div>

<div class="divider"></div>

<div class="row section">
  <div class="col s6">
    <h4>
      <%= link_to 'Details →', reports_balance_project_path(@project), class: 'btn-flat right' %>
      Balance History
    </h4>
    <div id="balance_chart">
    </div>
  </div>
  <div class="col s6">
    <h4>
      <%= link_to 'Details →', reports_spend_project_path(@project), class: 'btn-flat right' %>
      Spend
    </h4>
    <div id="spend_chart">
    </div>
  </div>
</div>

<div class="divider"></div>

<div class="row section">
  <div class="col s6">
    <h4>
      <%= link_to 'Details →', reports_income_outgoings_project_path(@project), class: 'btn-flat right' %>
      Income vs Outgoings
    </h4>
    <div id="income_outgoings_chart">
    </div>
  </div>
  <div class="col s6">
  </div>
</div>

<div class="fixed-action-btn">
  <a class="btn-floating btn-large red">
    <i class="large material-icons">menu</i>
  </a>
  <ul>
    <li>
      <a href="<%= new_project_account_path(@project) %>" class="btn-floating red tooltipped" data-position="left" data-tooltip="add account">
        <i class="material-icons">add</i>
      </a>
    </li>
    <li>
      <a href="#import-statements-modal" class="btn-floating yellow darken-2 tooltipped modal-trigger" data-position="left" data-tooltip="import statements">
        <i class="material-icons">file_upload</i>
      </a>
    </li>
    <li>
      <a href="<%= backup_project_path(@project) %>" class="btn-floating green tooltipped" data-position="left" data-tooltip="backup / restore">
        <i class="material-icons">archive</i>
      </a>
    </li>
    <li>
      <a href="<%= train_project_path(@project) %>" class="btn-floating blue tooltipped" data-position="left" data-tooltip="train classifier">
        <i class="material-icons">school</i>
      </a>
    </li>
  </ul>
</div>

<!-- Modal Structure -->
<div id="import-statements-modal" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Import Statements</h4>
    <p>Which account do you want to import statements for?</p>
    <div class="collection">
    <% @project.accounts.each do |account| %>
        <a href="<%= import_statement_account_path(account) %>" class="collection-item">
          <b><%= account.name %></b>
          <br>
          <%= I18n.t account.account_type %>
        </a>
    <% end %>
    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancel</a>
  </div>
</div>