config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  get 'projects/:id/statements', to: 'statements#index', as: 'project_statements'
  get 'projects/:id/statements/:date', to: 'statements#show', as: 'project_statement'
  get 'projects/:id/statements/:date/transactions', to: 'statements#transactions', as: 'statement_transactions'
  get 'projects/:id/statements/:date/summary', to: 'statements#summary', as: 'statement_summary'


  resources :projects do
    member do
      get 'backup', to: 'backup#index'
      get 'backup/download', to: 'backup#download'
      post 'backup/restore', to: 'backup#restore'

      get 'train', to: 'training#train'
      get 'preview', to: 'training#preview', as: 'training_preview'
      post 'classify', to: 'training#classify'

      get 'categories'

      get 'reports/spend', to: 'reports#spend'
      get 'reports/spend_data', to: 'reports#spend_data'
      get 'reports/balance', to: 'reports#balance'
      get 'reports/balance_data', to: 'reports#balance_data'
      get 'reports/income_outgoings', to: 'reports#income_outgoings'
      get 'reports/income_outgoings_data', to: 'reports#income_outgoings_data'
    end

    resources :accounts, shallow: true do
      resources :transactions, shallow: true do
        collection do
          get 'statement'
          get 'statement_summary'
        end
        member do
          post 'verify'
        end
      end
      member do
        get 'import_statement'
        post 'upload_statement'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy, :verify]
  before_action :set_account

  include TransactionsHelper

  # GET /transactions
  # GET /transactions.json
  def index
    @project = @account.project
    @month_options = month_options_for(@project)
  end

  def statement
    @transactions = @account.transactions.within_month(Date.parse(params[:month]))
    if params[:sort_by] == 'amount'
      @transactions = @transactions.by_amount
    else
      @transactions = @transactions.by_date
    end

    render partial: 'shared/transactions_table',
      locals: { transactions: @transactions, editable: true, classify: Proc.new{ |t| t.categorized_status } }
  end

  def statement_summary
    @transactions = @account.transactions.within_month(Date.parse(params[:month]))

    verification_state = VerificationState.new(@transactions).compute_state

    render partial: 'shared/verification_status',
      locals: { verification_state: verification_state, show_unverified_spend: true }
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    update_transaction { @transaction.update(transaction_params) }
  end

  def verify
    update_transaction { @transaction.verify(verified) }
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sync_confirm
    @transactions = Transaction.pending
  end

  def sync
    @pending_transactions = Transaction.pending
    @duplicate_transactions = []
    @saved_transactions = []
    @pending_transactions.each do |t|
      begin
        t.status = if t.category.nil? then :unclassified else :training end
        t.save
        @saved_transactions << t
      rescue ActiveRecord::RecordNotUnique => e
        @duplicate_transactions << t
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def set_account
      @account = @transaction.try(:account) || Account.find(params[:account_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:assigned_category)
    end

    def verified
      ActiveRecord::Type::Boolean.new.deserialize(params.require(:transaction).permit(:verified)[:verified])
    end

    def update_transaction
      respond_to do |format|
        if yield()
          format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
          format.json { render 'transactions/show.json.jbuilder' }
        else
          format.html { render :edit }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      end
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def month_options_for(project)
    transactions = project.transactions.order('date')
    first_date = transactions.first.date.beginning_of_month
    last_date = transactions.last.date
    DateRange.new(first_date,last_date, true).to_a
      .map{ |date| [date.strftime('%b %Y'), date.strftime('%Y-%m-%d')] }
  end

  def tr_sort_options
    [['Date', 'date'], ['Amount', 'amount']]
  end
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :transaction_date %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :transaction_type %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :transaction_description %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :transaction_value %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance, id: :transaction_balance %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :transaction_category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/import.html.erb
<% breadcrumb :import_transactions, @project %>

<h1>Import</h1>

<%= form_tag({action: :upload}, multipart: true) do %>
    <%= file_field_tag 'statement' %>
    <br>
    <%= submit_tag('Upload', class: 'waves-effect waves-light btn') %>
<% end %>

app/views/transactions/index.html.erb
<% breadcrumb :account_transactions, @account %>

<p id="notice"><%= notice %></p>

<h2><%= @account.name %></h2>

<script>
  function loadStatement() {
    var query = $('#statement_options').serialize();
    $('#transactions').load(`transactions/statement?${query}`, null, initializeCategoryForms);
  }

  function loadSummary() {
    var query = $('#statement_options').serialize();
    $('#summary').load(`transactions/statement_summary?${query}`);
  }

  function initializeCategoryForms() {
    function updateRow($tr, response) {
      var disableCheckbox = response.category != null;
      $tr.find('form.verified input[type=checkbox]').prop('disabled', disableCheckbox);
      $tr.removeClass('verified').addClass(response.verified_status);
    }

    $('.transactions form.category input[type=text]').change(function() {
      var $this = $(this);
      var action = $this.closest('form')[0].action + '.json';
      var data = $this.closest('form').serializeArray();
      $.post(action, data, function(response) {
        var autocompleteData = {};
        response.project_categories.forEach(function(val) {
          autocompleteData[val] = null;
        });
        $('.transactions form.category input[type=text]').autocomplete({
          data: autocompleteData,
          limit: 20, // The max amount of results that can be shown at once. Default: Infinity.
          onAutocomplete: function(val) {
            // Callback function when value is autcompleted.
          },
          minLength: 1, // The minimum length of the input for the autocomplete to start. Default: 1.
        });
        loadSummary();
        updateRow($this.closest('tr'), response);
      }, 'json');
    });
    $('.transactions form.verified input[type=checkbox]').change(function() {
      var $this = $(this);
      var action = $this.closest('form')[0].action + '.json';
      var data = $this.closest('form').serializeArray();
      $.post(action, data, function(response) {
        loadSummary();
        updateRow($this.closest('tr'), response);
      }, 'json');
    });
    $('.transactions form.category input[type=text]').autocomplete({
      data: <%=json_escape @project.categories.map{ |c| [c, nil] }.to_h.to_json.html_safe %>,
      limit: 20, // The max amount of results that can be shown at once. Default: Infinity.
      onAutocomplete: function(val) {
        // Callback function when value is autcompleted.
      },
      minLength: 1, // The minimum length of the input for the autocomplete to start. Default: 1.
    });

    $('.transactions form.category input[type=text]').focus(function() {
      $(this).closest('tr').addClass('highlight');
    });
    $('.transactions form.category input[type=text]').focusout(function() {
      $(this).closest('tr').removeClass('highlight');
    });
  }

  $(function() {


    loadStatement();
    loadSummary();

    $('#statement_options').change(function() {
      loadStatement();
      loadSummary();
    });
  });
</script>

<form id="statement_options" class="row">
  <div class="input-field col s3">
    <%= select_tag 'month', options_for_select(@month_options, @month_options.last[1]), id: 'month' %>
    <label>Month</label>
  </div>
  <div class="input-field col s3">
    <%= select_tag 'sort_by', options_for_select(tr_sort_options), id: 'sort_by' %>
    <label>Sort by</label>
  </div>
  <div id="summary" class="col s6">

  </div>
</form>

<div id="transactions">

</div>

<br>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Type:</strong>
  <%= @transaction.type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @transaction.value %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @transaction.balance %>
</p>

<p>
  <strong>Category:</strong>
  <%= @transaction.category %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/sync.html.erb
<p id="notice"><%= notice %></p>

<h1>Sync complete</h1>

<p>
  Synced <%= @saved_transactions.count %> transactions
</p>

<table class="transactions">
  <thead>
    <tr>
      <th class="date">Date</th>
      <th class="transaction_type">Type</th>
      <th class="description">Description</th>
      <th class="value">Value</th>
      <th class="balance">Balance</th>
      <th class="category">Category</th>
    </tr>
  </thead>

  <tbody>
    <% @saved_transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.date %></td>
          <td><%= transaction.transaction_type %></td>
          <td><%= transaction.description %></td>
          <td><%= transaction.value %></td>
          <td><%= transaction.balance %></td>
          <td><%= transaction.category %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<p>
  Unable to sync <%= @saved_transactions.count %> transactions
</p>

<table class="transactions">
  <thead>
    <tr>
      <th class="date">Date</th>
      <th class="transaction_type">Type</th>
      <th class="description">Description</th>
      <th class="value">Value</th>
      <th class="balance">Balance</th>
      <th class="category">Category</th>
    </tr>
  </thead>

  <tbody>
    <% @duplicate_transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.date %></td>
          <td><%= transaction.transaction_type %></td>
          <td><%= transaction.description %></td>
          <td><%= transaction.value %></td>
          <td><%= transaction.balance %></td>
          <td><%= transaction.category %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/transactions/sync_confirm.html.erb
<p id="notice"><%= notice %></p>

<h1>Pending Transactions</h1>

<%= button_to 'Sync', 'sync', { class: 'btn waves-effect waves-light'} %>

<p>
  <%= @transactions.count %> pending transactions
</p>

<table class="transactions">
  <thead>
    <tr>
      <th class="date">Date</th>
      <th class="transaction_type">Type</th>
      <th class="description">Description</th>
      <th class="value">Value</th>
      <th class="balance">Balance</th>
      <th class="category">Category</th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.date %></td>
          <td><%= transaction.transaction_type %></td>
          <td><%= transaction.description %></td>
          <td><%= transaction.value %></td>
          <td><%= transaction.balance %></td>
          <td><%= transaction.category %></td>
        </tr>
    <% end %>
  </tbody>
</table>