config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  get 'projects/:id/statements', to: 'statements#index', as: 'project_statements'
  get 'projects/:id/statements/:date', to: 'statements#show', as: 'project_statement'
  get 'projects/:id/statements/:date/transactions', to: 'statements#transactions', as: 'statement_transactions'
  get 'projects/:id/statements/:date/summary', to: 'statements#summary', as: 'statement_summary'


  resources :projects do
    member do
      get 'backup', to: 'backup#index'
      get 'backup/download', to: 'backup#download'
      post 'backup/restore', to: 'backup#restore'

      get 'train', to: 'training#train'
      get 'preview', to: 'training#preview', as: 'training_preview'
      post 'classify', to: 'training#classify'

      get 'categories'

      get 'reports/spend', to: 'reports#spend'
      get 'reports/spend_data', to: 'reports#spend_data'
      get 'reports/balance', to: 'reports#balance'
      get 'reports/balance_data', to: 'reports#balance_data'
      get 'reports/income_outgoings', to: 'reports#income_outgoings'
      get 'reports/income_outgoings_data', to: 'reports#income_outgoings_data'
    end

    resources :accounts, shallow: true do
      resources :transactions, shallow: true do
        collection do
          get 'statement'
          get 'statement_summary'
        end
        member do
          post 'verify'
        end
      end
      member do
        get 'import_statement'
        post 'upload_statement'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :project
  has_many :transactions

  TYPES = ['current', 'credit_card']

  scope :current, -> { where(account_type: 'current') }
  scope :credit_card, -> { where(account_type: 'credit_card') }

  def categories
    transactions.distinct.pluck(:assigned_category).compact
  end

  def balance_on(date)
    last_transaction = transactions.where('date <= ?', date).last
    last_transaction.try(:balance)
  end

  def income_between(from_date, to_date)
    if account_type == 'current'
      transactions.where('? <= date AND date < ? AND value > 0', from_date, to_date).sum(:value)
    else
      transactions.where('? <= date AND date < ? AND value < 0', from_date, to_date).sum(:value)
    end
  end

  def verification_state
    VerificationState.new(transactions).compute_state
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :import_statement, :upload_statement]
  before_action :set_project

  def import_statement

  end

  def upload_statement
    uploads = params[:statements]
    total_imports = 0
    total_duplicates = 0
    uploads.each do |upload|
      ext = File.extname(upload.original_filename)
      case
        when ext == '.csv'
          result = CsvStatementParser.new(@account).parse(upload.tempfile)
        when ext == '.pdf'
          result = PdfStatementParser.new(@account).parse(upload.tempfile)
        else
          raise "Unsupported file extension."
      end
      total_imports += result[:imported_transactions].count
      total_duplicates += result[:duplicate_transactions].count
    end
    notice = "Imported #{total_imports} transactions"
    notice << " (#{total_duplicates} duplicates)" if total_duplicates > 0
    redirect_to account_transactions_path(@account), notice: notice
  end

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = @project.accounts
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = @project.accounts.build
    @record = [@project, @account]
  end

  # GET /accounts/1/edit
  def edit
    @record = @account
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = @project.accounts.build(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        @record = [@project, @account]
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to project_accounts_url(@project), notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  def set_project
    @project = @account.try(:project) || Project.find(params[:project_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:name, :account_type)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@record) do |form| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :account_name %>
  </div>

  <div class="input-field">
    <%= form.select :account_type, Account::TYPES.map{ |t| [I18n.t(t), t]} %>
    <%= form.label :type %>
  </div>

  <div class="actions">
    <%= form.submit class: 'waves-effect waves-light btn' %>
    <%= link_to 'Cancel', @account.new_record? ? project_accounts_path(@project) : @account, class: 'waves-effect btn-flat' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<% breadcrumb :account, @account %>

<%= render 'form' %>

app/views/accounts/import_statement.html.erb
<% breadcrumb :import_statement, @account %>

<h1>Import</h1>

<%= form_tag({action: :upload_statement}, multipart: true) do %>
    <%= file_field_tag 'statements[]', multiple: true %>
    <br>
    <%= submit_tag('Upload', class: 'waves-effect waves-light btn') %>
<% end %>

app/views/accounts/index.html.erb
<% breadcrumb :project_accounts, @project %>

<p id="notice"><%= notice %></p>

<h1>Accounts</h1>



  <% @accounts.each do |account| %>
      <div class="row section accounts header">
        <div class="col s6">
          <h4>
            <%= account.name %>
            <%= link_to 'More →', project_accounts_path(@project), class: 'btn-flat right' %>
          </h4>
        </div>
        <div class="col s6"></div>
      </div>
      <div class="row">
        <div class="col s6">

          <%= account.account_type %>
          <%= link_to 'Show', account %>
          <%= link_to 'Edit', edit_account_path(account) %>
          <%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %>

        </div>
        <div class="col s6">
          <%= render partial: 'shared/verification_status',
              locals: { verification_state: account.verification_state, show_unverified_spend: true } %>
        </div>
      </div>
  <% end %>

<%= link_to 'New Account', new_project_account_path(@project) %>

app/views/accounts/new.html.erb
<% breadcrumb :project_accounts, @project %>

<h1>New Account</h1>

<%= render 'form' %>

app/views/accounts/show.html.erb
<% breadcrumb :account, @account %>

<div class="row">
  <div class="col s10">
    <h3><%= @account.name %></h3>
  </div>
  <div class="col s2">
    <%= link_to 'Edit', edit_account_path(@account), class: 'right btn-flat waves-effect' %>
  </div>
</div>

<div class="row">
  <div class="col s4">
    <ul class="collection with-header">
      <li class="collection-header"><h4>Reports</h4></li>

    </ul>
  </div>
  <div class="col s4">
    <ul class="collection with-header">
      <li class="collection-header"><h4>Transactions</h4></li>
      <li class="collection-item">
        <%= link_to 'Import Statement', import_statement_account_path(@account) %>
      </li>
      <li class="collection-item">
        <%= link_to 'View Transactions', account_transactions_path(@account) %>
      </li>
    </ul>
  </div>
  <div class="col s4">
    <p>
      <strong>Type:</strong>
      <%= @account.account_type %>
    </p>
  </div>
</div>